# .travis.yml file
language: node_js
node_js:
  
  - "12"
  
services: mongodb  
cache:  
  directories:
  - "node_modules"
install:
  - npm install
script:
  
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master  

# //Made a comment in the .travis.yml file to be sure that TravisCI is automatically deploying my project
